ALTER TABLE AEROPUERTO ADD PRIMARY KEY (CodIATA, Ciudad);/*Es primary key porque una ciudad no puede tener dos mismos código IATA*/
ALTER TABLE AEROPUERTO ADD UNIQUE(Nombre);/*No puede haber dos aeropuertos con el mismo nombre*/
ALTER TABLE TERMINAL ADD PRIMARY KEY(Numero);
ALTER TABLE TERMINAL ADD CONSTRAINT FK_AEROPUERTO FOREIGN KEY(CodIATA_Aeropuerto,Ciudad_Aeropuerto) REFERENCES AEROPUERTO(CodIATA,Ciudad) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE VUELO ADD PRIMARY KEY(CodVuelo);
ALTER TABLE COMPAÑIA ADD PRIMARY KEY(CodCompañia);
ALTER TABLE VUELO ADD CONSTRAINT FK_COMPANIA FOREIGN KEY(CodCompañia) REFERENCES COMPAÑIA(CodCompañia) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE ASIENTO ADD PRIMARY KEY(CodAsiento);
ALTER TABLE PASAJERO ADD PRIMARY KEY(DNI);
ALTER TABLE RESERVA ADD PRIMARY KEY(Localizador);
ALTER TABLE RESERVA ADD CONSTRAINT FK_PASAJERO FOREIGN KEY(DNI_PASAJERO) REFERENCES PASAJERO(DNI) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESERVA_VUELO ADD PRIMARY KEY(Localizador_RESERVA,CodVuelo_VUELO,CodAsiento_ASIENTO);
ALTER TABLE RESERVA_VUELO ADD CONSTRAINT FK_RESERVA FOREIGN KEY(Localizador_RESERVA) REFERENCES RESERVA(Localizador) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESERVA_VUELO ADD CONSTRAINT FK_VUELO FOREIGN KEY(CodVuelo_VUELO) REFERENCES VUELO(CodVuelo) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE RESERVA_VUELO ADD CONSTRAINT FK_ASIENTO FOREIGN KEY(CodAsiento_ASIENTO) REFERENCES ASIENTO(CodAsiento) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE HORARIO ADD PRIMARY KEY(CodVuelo_VUELO,HoraFechaSalida,HoraFechaLlegada);
ALTER TABLE HORARIO ADD CONSTRAINT FK_VUELO1 FOREIGN KEY(CodVuelo_VUELO) REFERENCES VUELO(CodVuelo) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FACTURACION ADD CONSTRAINT FK_TERMINAL FOREIGN KEY(Numero_TERMINAL) REFERENCES TERMINAL(Numero) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FACTURACION ADD CONSTRAINT FK_AEROPUERTO1 FOREIGN KEY(CodIATA_AEROPUERTO,Ciudad_AEROPUERTO) REFERENCES AEROPUERTO(CodIATA,Ciudad) ON DELETE CASCADE ON UPDATE CASCADE;
