DROP DATABASE IF EXISTS VOYVOLANDO;
CREATE DATABASE VOYVOLANDO;
USE VOYVOLANDO
CREATE TABLE AEROPUERTO(
			CodIATA CHAR(3), 
			Nombre VARCHAR(50), 
			Ciudad VARCHAR(30), 
			Pais VARCHAR(30)
			);

CREATE TABLE TERMINAL(
			Numero VARCHAR(5),  
			CodIATA_Aeropuerto CHAR(3), 
			Ciudad_Aeropuerto VARCHAR(30));

CREATE TABLE VUELO(
			CodVuelo VARCHAR(7), 
			CodCompañia CHAR(3), 
			AeropuertoOrigen VARCHAR(50), 
			AeropuertoDestino VARCHAR(50), 
			Estado ENUM('Situado','Cancelado','Retrasado'), 
			PuertaEmbarque INT, 
			PuertaLlegada INT
		);

CREATE TABLE ASIENTO(
			CodAsiento VARCHAR(3), 
			TipoClase ENUM('Business','Turista')
			);

CREATE TABLE PASAJERO(
			DNI CHAR(9), 
			Nombre VARCHAR(30), 
			Apellido1 VARCHAR(30), 
			Apellido2 VARCHAR(30),
			EdadPasajero ENUM('Adulto','Niño','Bebe')	
			);

CREATE TABLE RESERVA(
			Localizador CHAR(9),
			DNI CHAR(9),
			Precio FLOAT,
			metodoPago ENUM('Tarjeta','Efectivo') 
			);

CREATE TABLE RESERVA_VUELO(
			Localizador VARCHAR(20), 
			CodVuelo VARCHAR(7)
			);

CREATE TABLE COMPAÑIA(
			CodCompañia CHAR(3), 
			Nombre VARCHAR(30), 
			Logo BLOB
			);

CREATE TABLE HORARIO(
			CodVuelo VARCHAR(7), 
			HoraFechaSalida TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 				HoraFechaLlegada TIMESTAMP  DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
			);
CREATE TABLE FACTURACION(
			Mostrador INT, 
			NumeroTerminal VARCHAR(5), 
			CiudadAeropuerto VARCHAR(30), 
                        CodIATA CHAR(3)
			HoraLimite TIME, 
			Fecha DATE
			);
ALTER TABLE AEROPUERTO ADD PRIMARY KEY (CodIATA, Ciudad);
ALTER TABLE AEROPUERTO ADD UNIQUE(Nombre);
ALTER TABLE TERMINAL ADD PRIMARY KEY(Numero,CodIATA,Ciudad);
ALTER TABLE TERMINAL ADD FOREIGN KEY(CodIATA,Ciudad) REFERENCES AEROPUERTO(CodIATA,Ciudad) ON DELETE SET NULL ON UPDATE CASCADE
ALTER TABLE VUELO ADD PRIMARY KEY(CodVuelo );
ALTER TABLE VUELO ADD FOREIGN KEY(CodCompañia) REFERENCES COMPAÑIA(CodCompañia) ON DELETE SET NULL ON UPDATE CASCADE);
ALTER TABLE ASIENTO ADD PRIMARY KEY(CodAsiento );
ALTER TABLE PASAJERO ADD PRIMARY KEY(DNI, Nombre);
ALTER TABLE RESERVA ADD PRIMARY KEY(Localizador, DNI);
ALTER TABLE RESERVA ADD FOREIGN KEY(DNI) REFERENCES PASAJERO(DNI) ON DELETE SET NULL ON UPDATE CASCADE);
ALTER TABLE RESERVA_VUELO ADD PRIMARY KEY(LOCALIZADOR, CodVuelo);
ALTER TABLE RESERVA_VUELO ADD FOREIGN KEY(DNI) REFERENCES PASAJERO(DNI) ON DELETE SET NULL ON UPDATE CASCADE);
ALTER TABLE COMPAÑIA ADD PRIMARY KEY(CodCompañia);
ALTER TABLE HORARIO ADD PRIMARY KEY(CodVuelo, HoraFechaSalida, HoraFechaLlegada);
ALTER TABLE HORARIO ADD FOREIGN KEY(CodVuelo) REFERENCES VUELO(CodVuelo) ON DELETE SET NULL ON UPDATE CASCADE);
ALTER TABLE FACTURACION ADD PRIMARY KEY(NumeroTerminal, CiudadAeropuerto, CodIATA);
ALTER TABLE FACTURACION ADD FOREIGN KEY(NumeroTerminal) REFERENCES TERMINAL(NumeroTerminal) ON DELETE SET NULL ON UPDATE CASCADE);
ALTER TABLE FACTURACION ADD FOREIGN KEY(CiudadAeropuerto, CodIATA) REFERENCES AEROPUERTO(CiudadAeropuerto) ON DELETE SET NULL ON UPDATE CASCADE);

