INSERT INTO AEROPUERTO VALUES('MAD','Barajas-Adolfo Suarez','Madrid','España'),('LHR','Heathrow','Londres','Inglaterra'),('CDG','Paris-Charles de Gualle','Paris','Francia'),('MEX','Benito Juarez','Ciudad de Mexico','Mexico'),('BCN','El Prat','El Prat de Llobregat','España');
INSERT INTO TERMINAL VALUES(2),(),(),(),();
INSERT INTO VUELO VALUES(),(),(),(),();
INSERT INTO ASIENTO VALUES(),(),(),(),();
INSERT INTO PASAJERO VALUES(),(),(),(),();
INSERT INTO RESERVA VALUES(),(),(),(),();
INSERT INTO RESERVA_VUELO VALUES(),(),(),(),();
INSERT INTO COMPAÑIA VALUES(),(),(),(),();
INSERT INTO HORARIO VALUES(),(),(),(),();
INSERT INTO FACTURACION VALUES(),(),(),(),();
